/*
 * Nobel Prize Master Data
 *
 * Information about the Nobel Prizes and the Nobel Prize Laureates
 *
 * API version: 2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// City and county at the time, citynow and countrynow are as up to date names. Continent as geonames.org standard. LocationString is the combination of city, country, citynow and country now.
type Location struct {

	City *Translation `json:"city,omitempty"`

	Country *Translation `json:"country,omitempty"`

	CityNow *TranslationWithSameas `json:"cityNow,omitempty"`

	CountryNow *TranslationWithSameas `json:"countryNow,omitempty"`

	Continent *Translation `json:"continent,omitempty"`

	LocationString *Translation `json:"locationString,omitempty"`
}
