/*
 * Nobel Prize Master Data
 *
 * Information about the Nobel Prizes and the Nobel Prize Laureates
 *
 * API version: 2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type LaureateWikidata struct {

	// Wikidata id
	Id string `json:"id,omitempty"`

	// URL to wikidata entry
	Url string `json:"url,omitempty"`
}
