/*
 * Nobel Prize Master Data
 *
 * Information about the Nobel Prizes and the Nobel Prize Laureates
 *
 * API version: 2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type LaureateWikipedia struct {

	// Wikipedia url slug
	Slug string `json:"slug,omitempty"`

	// URL to english wikipedia page
	English string `json:"english,omitempty"`
}
