/*
 * Nobel Prize Master Data
 *
 * Information about the Nobel Prizes and the Nobel Prize Laureates
 *
 * API version: 2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Laureate's full information and their respectives awarded Prizes
type Laureate struct {

	Id int32 `json:"id,omitempty"`

	LaureateIfPerson *Person `json:"laureateIfPerson,omitempty"`

	LaureateIfOrg *Organization `json:"laureateIfOrg,omitempty"`

	Wikipedia *LaureateWikipedia `json:"wikipedia,omitempty"`

	Wikidata *LaureateWikidata `json:"wikidata,omitempty"`

	SameAs []Urls `json:"sameAs,omitempty"`

	Links []ItemLinks `json:"links,omitempty"`

	NobelPrizes []NobelPrizePerLaureate `json:"nobelPrizes,omitempty"`
}
