/*
 * Nobel Prize Master Data
 *
 * Information about the Nobel Prizes and the Nobel Prize Laureates
 *
 * API version: 2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ItemLinks struct {

	Rel string `json:"rel,omitempty"`

	Href string `json:"href,omitempty"`

	Action string `json:"action,omitempty"`

	Types string `json:"types,omitempty"`
}
