/*
 * Nobel Prize Master Data
 *
 * Information about the Nobel Prizes and the Nobel Prize Laureates
 *
 * API version: 2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Links struct {

	First string `json:"first,omitempty"`

	Prev string `json:"prev,omitempty"`

	Self string `json:"self,omitempty"`

	Next string `json:"next,omitempty"`

	Last string `json:"last,omitempty"`
}
