/*
 * Nobel Prize Master Data
 *
 * Information about the Nobel Prizes and the Nobel Prize Laureates
 *
 * API version: 2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type NobelPrizesMeta struct {

	Offset int32 `json:"offset,omitempty"`

	Limit int32 `json:"limit,omitempty"`

	NobelPrizeYear int32 `json:"nobelPrizeYear,omitempty"`

	YearTo int32 `json:"yearTo,omitempty"`

	NobelPrizeCategory string `json:"nobelPrizeCategory,omitempty"`

	Count int32 `json:"count,omitempty"`
}
