/*
 * Nobel Prize Master Data
 *
 * Information about the Nobel Prizes and the Nobel Prize Laureates
 *
 * API version: 2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Organization struct {

	OrgName *Translation `json:"orgName,omitempty"`

	NativeName string `json:"nativeName,omitempty"`

	Acronym string `json:"acronym,omitempty"`

	Founded *Event `json:"founded,omitempty"`

	Dissolution *Event `json:"dissolution,omitempty"`

	Headquarters *Location `json:"headquarters,omitempty"`
}
