/*
 * Nobel Prize Master Data
 *
 * Information about the Nobel Prizes and the Nobel Prize Laureates
 *
 * API version: 2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type LaureatesMeta struct {

	Offset int32 `json:"offset,omitempty"`

	Limit int32 `json:"limit,omitempty"`

	Sort string `json:"sort,omitempty"`

	ID int32 `json:"ID,omitempty"`

	Name string `json:"name,omitempty"`

	Gender string `json:"gender,omitempty"`

	Motivation string `json:"motivation,omitempty"`

	Affiliation string `json:"affiliation,omitempty"`

	Residence string `json:"residence,omitempty"`

	BirthDate string `json:"birthDate,omitempty"`

	BirthDateTo string `json:"birthDateTo,omitempty"`

	DeathDate string `json:"deathDate,omitempty"`

	DeathDateTo string `json:"deathDateTo,omitempty"`

	FoundedDate string `json:"foundedDate,omitempty"`

	BirthCity string `json:"birthCity,omitempty"`

	BirthCountry string `json:"birthCountry,omitempty"`

	BirthContinent string `json:"birthContinent,omitempty"`

	DeathCity string `json:"deathCity,omitempty"`

	DeathCountry string `json:"deathCountry,omitempty"`

	DeathContinent string `json:"deathContinent,omitempty"`

	FoundedCity string `json:"foundedCity,omitempty"`

	FoundedCountry string `json:"foundedCountry,omitempty"`

	FoundedContinent string `json:"foundedContinent,omitempty"`

	HeadquartersCity string `json:"headquartersCity,omitempty"`

	HeadquartersCountry string `json:"headquartersCountry,omitempty"`

	HeadquartersContinent string `json:"headquartersContinent,omitempty"`

	NobelPrizeYear int32 `json:"nobelPrizeYear,omitempty"`

	YearTo int32 `json:"yearTo,omitempty"`

	NobelPrizeCategory string `json:"nobelPrizeCategory,omitempty"`

	Count int32 `json:"count,omitempty"`
}
