/*
 * Nobel Prize Master Data
 *
 * Information about the Nobel Prizes and the Nobel Prize Laureates
 *
 * API version: 2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Model containing Nobel Prize information
type NobelPrize struct {

	AwardYear int32 `json:"awardYear,omitempty"`

	Category *Translation `json:"category,omitempty"`

	CategoryFullName *Translation `json:"categoryFullName,omitempty"`

	DateAwarded string `json:"dateAwarded,omitempty"`

	// Prize amount given at the year of the award
	PrizeAmount int32 `json:"prizeAmount,omitempty"`

	// Prize amount adjusted according to Index number yearly average
	PrizeAmountAdjusted int32 `json:"prizeAmountAdjusted,omitempty"`

	TopMotivation *Translation `json:"topMotivation,omitempty"`

	Laureates []LaureateBasic `json:"laureates,omitempty"`
}
