/*
 * Nobel Prize Master Data
 *
 * Information about the Nobel Prizes and the Nobel Prize Laureates
 *
 * API version: 2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Fullname is the combination of given and family name
type Person struct {

	KnownName *Translation `json:"knownName,omitempty"`

	GivenName *Translation `json:"givenName,omitempty"`

	FamilyName *Translation `json:"familyName,omitempty"`

	FullName *Translation `json:"fullName,omitempty"`

	// Short slug version of familyname used in filenames
	Filename string `json:"filename,omitempty"`

	// Only for some Laureates in Literature category
	Penname string `json:"penname,omitempty"`

	Gender string `json:"gender,omitempty"`

	Birth *Event `json:"birth,omitempty"`

	Death *Event `json:"death,omitempty"`
}
