/*
 * Nobel Prize Master Data
 *
 * Information about the Nobel Prizes and the Nobel Prize Laureates
 *
 * API version: 2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Description of the Nobel Prize by Laureate
type NobelPrizePerLaureate struct {

	AwardYear int32 `json:"awardYear,omitempty"`

	Category *Translation `json:"category,omitempty"`

	CategoryFullName *Translation `json:"categoryFullName,omitempty"`

	SortOrder string `json:"sortOrder,omitempty"`

	Portion string `json:"portion,omitempty"`

	DateAwarded string `json:"dateAwarded,omitempty"`

	PrizeStatus string `json:"prizeStatus,omitempty"`

	Motivation *Translation `json:"motivation,omitempty"`

	// Prize amount given at the year of the award
	PrizeAmount int32 `json:"prizeAmount,omitempty"`

	// Prize amount adjusted according to Index number yearly average
	PrizeAmountAdjusted int32 `json:"prizeAmountAdjusted,omitempty"`

	Affiliations []Entity `json:"affiliations,omitempty"`

	Residences []Residence `json:"residences,omitempty"`

	Links []ItemLinks `json:"links,omitempty"`
}
